version: "3.8"
services:

  sparray:
    build: ./
    container_name: sparray
    volumes:
      - ./:/usr/src/app
      - sparray_node_modules:/usr/src/app/node_modules


volumes:
  sparray_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules